# Generated by Django 3.2.4 on 2021-07-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramen',
            name='ingredient',
            field=models.ManyToManyField(to='main_app.Ingredient'),
        ),
    ]
